webchat/chat/urls.py
from django.urls import path
from chat import views


app_name = 'chat'
urlpatterns = [
	path("rooms/", views.rooms, name="rooms"),
	path("rooms/<str:room_name>/", views.room, name="room"),
    
	path("chat/", views.chat, name="chat"),
	path("ajax_send_message", views.ajax_send_message, name="ajax_send_message"),
]

webchat/home/urls.py
from django.urls import path
from home import views


app_name = 'home'
urlpatterns = [
	path('', views.index, name='index'),
]

webchat/chat/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Message(models.Model):
	text = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	file = models.FileField(upload_to='uploads/', blank=True, null=True)
	time = models.DateTimeField(auto_now_add=True)
	blimpo = models.CharField(max_length=100, blank=True, null=True)

	class Meta:
		verbose_name_plural = "Messages"

	def __str__(self):
		return self.text

	def as_dict(self):
		if self.time:
			time = self.time.strftime("%H:%M")
		else:
			time = ""

		return({
			"pk": self.pk,
			"text": self.text,
			"author": self.author,
			"file": self.file,
			"time": time,
		})

webchat/home/models.py
from django.db import models

# Create your models here.

webchat/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from chat.models import Message
from django.http import JsonResponse

MEDIA_URL = '/media/'


@login_required
def rooms(request):
	return render(request, "chat/index.html")


@login_required
def room(request, room_name):
	context_dict = {}

	context_dict['room_name'] = room_name
	return render(request, "chat/room.html", context_dict)


@login_required
def chat(request):
	context_dict = {}

	messages = Message.objects.all()
	msgs = []
	for m in messages:
		msgs.append(m.as_dict())

	context_dict['messages'] = msgs
	context_dict['MEDIA_URL'] = MEDIA_URL
	return render(request, "chat/chat.html", context_dict)


@login_required
def ajax_send_message(request):
	data = {}
	if request.method == 'POST':
		postdata = request.POST
		text = postdata.get("message")
		has_file = int(postdata.get("has_file"))

		try:
			message = Message()

			message.text = text
			message.author = request.user
			if has_file:
				message.file = request.FILES["file"]

			message.save()
			data['filename'] = message.file.name
			data['result'] = 0
		except:
			data['result'] = -1
	return JsonResponse(data)

webchat/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context_dict = {}

	return render(request, "home/home.html", context_dict)

webchat/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<meta charset="utf-8">

		<!-- Title -->
		<link rel="shortcut icon" href="{% static 'favicon.ico' %}?{% now 'U' %}"/>
		<title>
			{% block title_block %}
				webchat
			{% endblock %}
		</title>

		<!-- Styles -->
		{% block stylesheets %}
			<link href="{% static "css/custom.css" %}" rel="stylesheet"/>
		{% endblock %}

		<!-- Scripts (will execute when entering all pages) -->
		{% block headscript_block %}
		{% endblock %}
	</head>

	<body>
		<!-- Main Content -->
		{% block body_block %}
		{% endblock %}

		<!-- Scripts -->
		{% block scripts %}
			<script src="{% static "jquery/jquery-3.6.3.min.js" %}"></script>
			<script src="{% static "js/common.js" %}?{% now 'U' %}"></script>
		{% endblock %}

		{% block extrascripts %}
		{% endblock %}
	</body>
</html>

webchat/templates/chat/chat.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
	Chat
{% endblock %}

{% block body_block %}
	<link href="{% static "css/chat.css" %}?{% now 'U' %}" rel="stylesheet"/>

	<div id="chat">
		<div id="messages">
			{% for m in messages %}
				<div class="message"
				{% if m.author == request.user %}my-msg{% endif %}
				{% if m.file %}attach-msg{% endif %}>
					<div class="msg-sender">
						{{ m.author }}
					</div>

					<div class="msg-text">
						{% if m.text %}
							{{ m.text }}
						{% endif %}

						{% if m.file %}
							<a target="_blank" href="{{ MEDIA_URL }}{{ m.file }}">
								<img src="{% static 'images/Attachment.png' %}">
							</a>
						{% endif %}
					</div>

					<div class="msg-time">
						{{ m.time }}
					</div>
				</div>
			{% endfor %}
		</div>

		<div id="textbox">
			<div id="filearea">
				<input type="file" id="new-msg-file" accept="image/*" hidden>
				<button id="rem-file">
					<img src="{% static 'images/Trash.png' %}">
				</button>
			</div>

			<div id="the-rest">
				<button id="attach-btn">
					<img src="{% static 'images/Attachment.png' %}">
				</button>

				<textarea id="new-msg" class="form-control" rows="1" onkeyup="msg_fit(this)"></textarea>

				<button id="send-btn">
					<img src="{% static 'images/Send.png' %}">
				</button>
			</div>
		</div>
	</div>
{% endblock %}

{% block footer_block %}
{% endblock %}

{% block extrascripts %}
	<script src="{% static "js/chat.js" %}?{% now 'U' %}"></script>

	<script>
		function ajax_send_message(){
			let message = $("#new-msg").val();
			let file = document.getElementById("new-msg-file").files[0];
			let has_file = 0;
			if (file)
				has_file++;

			var formData = new FormData();
			formData.append("csrfmiddlewaretoken", "{{ csrf_token }}");
			formData.append("message", message);
			formData.append("has_file", has_file);
			formData.append("file", file);

			console.log('Ajax add message')
			$.ajax({
				type: "POST",
				enctype: 'multipart/form-data',
				url: "{% url "chat:ajax_send_message" %}",
				data: formData,
				processData: false,
				contentType: false,
				cache: false,
				timeout: 10000,
				success: function (data) {
					if (data.result == 0){
						console.log('Success');
						add_message(data.filename);
					}
					else console.log('Failure');
				},
				error: function (e) {
					console.log('Error');
				}
			});
		}

		function add_message(filename){
			var msg = document.createElement("div");
			var currentdate = new Date();
			var date = currentdate.getDate() + "/"
						+ (currentdate.getMonth()+1) + " "
						+ currentdate.getHours() + ":"
						+ currentdate.getMinutes();

			msg.className = "message"
			setAttributes(msg, {"my-msg": ""});

			if (document.getElementById("new-msg-file").files[0])
				var message = `
				<div class="msg-text">
					_message_
					<a target="_blank" href="{{ MEDIA_URL }}_file_">
						<img src="{% static 'images/Attachment.png' %}">
					</a>
				</div>`.replace("_message_", $("#new-msg").val()).replace("_file_", filename);
			else
				var message = `
				<div class="msg-text">
					_message_
				</div>`.replace("_message_", $("#new-msg").val());

			msg.innerHTML = `
				<div class="msg-sender">
					_user_
				</div>

				<div class="msg-text">
					_message_
				</div>

				<div class="msg-time">
					_date_
				</div>`.replace("_user_", "{{ request.user.username }}").replace("_message_", message).replace("_date_", date);

			$("#messages").append(msg);
			clear_img_preview();
			$("#new-msg").val("");
			goto_last_msg();
		}
	</script>
{% endblock %}

webchat/templates/chat/index.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
	Chat
{% endblock %}


{% block body_block %}
	What chat room would you like to enter?<br>
	<input id="room-name-input" type="text" size="100"><br>
	<input id="room-name-submit" type="button" value="Enter">
{% endblock %}

{% block extrascripts %}
	<script src="{% static "js/index.js" %}?{% now 'U' %}"></script>
{% endblock %}

webchat/templates/chat/room.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
	{{ room_name }}
{% endblock %}

{% block body_block %}
	<textarea id="chat-log" cols="100" rows="20"></textarea><br>

	<input id="chat-message-input" type="text" size="100"><br>
	<input id="chat-message-submit" type="button" value="Send">
	{{ room_name|json_script:"room-name" }}
{% endblock %}

{% block extrascripts %}
	<script src="{% static "js/room.js" %}?{% now 'U' %}"></script>
{% endblock %}

webchat/templates/home/home.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
	{% if request.user.username %}
		<h1>Hi {{ request.user.username }}</h1>
		<a href="{% url 'chat:rooms' %}">Rooms</a>
		<a href="{% url 'chat:chat' %}">Chat</a>
		<a href="{% url 'logout' %}">Logout</a>

	{% else %}
		<h1>Hi Guest</h1>
		<a href="{% url 'login' %}">Log in</a>
	{% endif %}
</div>
{% endblock %}